import type { Jugador, Partido, Producto } from "./types";

export const mockJugadores: Jugador[] = [
  { id: "1", nombre: "Martín", apellido: "Rodríguez", posicion: "Arquero", numero: 1, edad: 28 },
  { id: "2", nombre: "Sebastián", apellido: "González", posicion: "Arquero", numero: 12, edad: 24 },
  { id: "3", nombre: "Lucas", apellido: "Fernández", posicion: "Defensor", numero: 2, edad: 26 },
  { id: "4", nombre: "Nicolás", apellido: "López", posicion: "Defensor", numero: 3, edad: 29 },
  { id: "5", nombre: "Diego", apellido: "Martínez", posicion: "Defensor", numero: 4, edad: 27 },
  { id: "6", nombre: "Facundo", apellido: "Pérez", posicion: "Defensor", numero: 5, edad: 25 },
  { id: "7", nombre: "Matías", apellido: "García", posicion: "Defensor", numero: 6, edad: 23 },
  { id: "8", nombre: "Santiago", apellido: "Álvarez", posicion: "Mediocampista", numero: 7, edad: 26 },
  { id: "9", nombre: "Ramiro", apellido: "Torres", posicion: "Mediocampista", numero: 8, edad: 28 },
  { id: "10", nombre: "Tomás", apellido: "Ruiz", posicion: "Mediocampista", numero: 10, edad: 24 },
  { id: "11", nombre: "Agustín", apellido: "Sánchez", posicion: "Mediocampista", numero: 14, edad: 22 },
  { id: "12", nombre: "Bruno", apellido: "Herrera", posicion: "Mediocampista", numero: 15, edad: 27 },
  { id: "13", nombre: "Franco", apellido: "Morales", posicion: "Mediocampista", numero: 16, edad: 25 },
  { id: "14", nombre: "Ezequiel", apellido: "Romero", posicion: "Delantero", numero: 9, edad: 26 },
  { id: "15", nombre: "Iván", apellido: "Díaz", posicion: "Delantero", numero: 11, edad: 23 },
  { id: "16", nombre: "Leandro", apellido: "Castro", posicion: "Delantero", numero: 17, edad: 29 },
  { id: "17", nombre: "Rodrigo", apellido: "Vargas", posicion: "Delantero", numero: 18, edad: 21 },
  { id: "18", nombre: "Emiliano", apellido: "Medina", posicion: "Delantero", numero: 19, edad: 24 },
];

const hoy = new Date();
const d = (days: number) => {
  const date = new Date(hoy);
  date.setDate(date.getDate() + days);
  return date.toISOString().split("T")[0];
};

export const mockPartidos: Partido[] = [
  {
    id: "1",
    rival: "Estudiantes FC",
    fecha: d(5),
    hora: "16:00",
    sede: "Estadio Elbio Universitario",
    es_local: true,
    estado: "programado",
    competencia: "Liga Regional",
    categoria: "Mayor",
  },
  {
    id: "2",
    rival: "Atlético Central",
    fecha: d(12),
    hora: "18:30",
    sede: "Estadio Municipal Norte",
    es_local: false,
    estado: "programado",
    competencia: "Copa Provincial",
    categoria: "Mayor",
  },
  {
    id: "3",
    rival: "Deportivo Sur",
    fecha: d(19),
    hora: "15:00",
    sede: "Estadio Elbio Universitario",
    es_local: true,
    estado: "programado",
    competencia: "Liga Regional",
    categoria: "Reserva",
  },
  {
    id: "4",
    rival: "Unión Académica",
    fecha: d(26),
    hora: "17:00",
    sede: "Estadio Unión",
    es_local: false,
    estado: "programado",
    competencia: "Liga Regional",
    categoria: "Sub 20",
  },
  {
    id: "5",
    rival: "Racing Universitario",
    fecha: d(-7),
    hora: "16:00",
    sede: "Estadio Elbio Universitario",
    es_local: true,
    estado: "finalizado",
    resultado_local: 3,
    resultado_visitante: 1,
    competencia: "Liga Regional",
    categoria: "Mayor",
  },
  {
    id: "6",
    rival: "Ferro Estudiantil",
    fecha: d(-14),
    hora: "18:00",
    sede: "Estadio Ferro",
    es_local: false,
    estado: "finalizado",
    resultado_local: 1,
    resultado_visitante: 1,
    competencia: "Copa Provincial",
    categoria: "Mayor",
  },
  {
    id: "7",
    rival: "Platense Académico",
    fecha: d(-21),
    hora: "15:30",
    sede: "Estadio Elbio Universitario",
    es_local: true,
    estado: "finalizado",
    resultado_local: 2,
    resultado_visitante: 0,
    competencia: "Liga Regional",
    categoria: "Reserva",
  },
];

export const mockProductos: Producto[] = [
  {
    id: "1",
    nombre: "Camiseta Titular 2025",
    descripcion: "Camiseta oficial del equipo, temporada 2025. Tecnología de secado rápido.",
    precio: 18500,
    foto_url: "",
    categoria: "Camisetas",
    talles: ["S", "M", "L", "XL", "XXL"],
    stock: 50,
    destacado: true,
  },
  {
    id: "2",
    nombre: "Camiseta Alternativa 2025",
    descripcion: "Camiseta alternativa temporada 2025. Diseño exclusivo edición limitada.",
    precio: 18500,
    foto_url: "",
    categoria: "Camisetas",
    talles: ["S", "M", "L", "XL"],
    stock: 30,
    destacado: true,
  },
  {
    id: "3",
    nombre: "Camiseta Retro 2013",
    descripcion: "Edición especial conmemorativa del título Divisional C.",
    precio: 22000,
    foto_url: "",
    categoria: "Camisetas",
    talles: ["S", "M", "L", "XL"],
    stock: 15,
    destacado: true,
  },
  {
    id: "4",
    nombre: "Short Oficial",
    descripcion: "Short oficial del equipo, mismo modelo que usa el plantel profesional.",
    precio: 9500,
    foto_url: "",
    categoria: "Shorts",
    talles: ["S", "M", "L", "XL", "XXL"],
    stock: 40,
  },
  {
    id: "5",
    nombre: "Short Training",
    descripcion: "Short de entrenamiento con bolsillos laterales.",
    precio: 7800,
    foto_url: "",
    categoria: "Shorts",
    talles: ["S", "M", "L", "XL"],
    stock: 35,
  },
  {
    id: "6",
    nombre: "Bufanda Oficial",
    descripcion: "Bufanda tejida con los colores del club.",
    precio: 4500,
    foto_url: "",
    categoria: "Accesorios",
    talles: [],
    stock: 100,
  },
  {
    id: "7",
    nombre: "Gorra EU",
    descripcion: "Gorra con logo bordado del club. Regulable, talle único.",
    precio: 5200,
    foto_url: "",
    categoria: "Accesorios",
    talles: [],
    stock: 60,
  },
  {
    id: "8",
    nombre: "Mochila Club",
    descripcion: "Mochila oficial con compartimentos para botines.",
    precio: 14900,
    foto_url: "",
    categoria: "Accesorios",
    talles: [],
    stock: 20,
  },
  {
    id: "9",
    nombre: "Medias Oficiales",
    descripcion: "Medias de juego oficiales, pack x2 pares.",
    precio: 3200,
    foto_url: "",
    categoria: "Accesorios",
    talles: [],
    stock: 80,
  },
];
